export type ParameterDescriptor = (value: number) => string;

export const parameterDescriptors = {
  raw: (value: number) => value.toString(),
  singleDual: (value: number) => value === 0 ? "Single" : "Dual",
  signedTwoByte: (value: number): string => {
    if (value & 0x80) {
      return ((value & 0x7F) - 0x80).toString();
    }
    return value.toString();
  },
  assignKnob: (value: number) => {
    const assignKnobParameterList = [
      "NoAssign",
      "Timbre1 Unison Detune",
      "Timbre1 Unison Spread",
      "Timbre1 Porta Time",
      "Timbre1 Trans",
      "Timbre1 FineTune",
      "Timbre1 Level",
      "Timbre1 Pan",
      "Timbre1 OSC1 Wave",
      "Timbre1 OSC1 Shape",
      "Timbre1 OSC1 OSC Mod",
      "Timbre1 OSC1 Semitone",
      "Timbre1 OSC1 FineTune",
      "Timbre1 OSC1 Level",
      "Timbre1 OSC2 Wave",
      "Timbre1 OSC2 Shape",
      "Timbre1 OSC2 OSC Mod",
      "Timbre1 OSC2 Semitone",
      "Timbre1 OSC2 FineTune",
      "Timbre1 OSC2 Level",
      "Timbre1 OSC3 Wave",
      "Timbre1 OSC3 Shape",
      "Timbre1 OSC3 Semitone",
      "Timbre1 OSC3 FineTune",
      "Timbre1 OSC3 Level",
      "Timbre1 Noise Type",
      "Timbre1 Noise Color",
      "Timbre1 Noise Level",
      "Timbre1 Filter Type",
      "Timbre1 Filter Cutoff",
      "Timbre1 Filter Reso",
      "Timbre1 Filter Drive",
      "Timbre1 Filter Keytrack",
      "Timbre1 AmpEG Attack",
      "Timbre1 AmpEG Decay",
      "Timbre1 AmpEG Sustain",
      "Timbre1 AmpEG Release",
      "Timbre1 AmpEG VeloSens",
      "Timbre1 FltEG Attack",
      "Timbre1 FltEG Decay",
      "Timbre1 FltEG Sustain",
      "Timbre1 FltEG Release",
      "Timbre1 FltEG Int",
      "Timbre1 LFO1 Freq",
      "Timbre1 LFO1 Smooth",
      "Timbre1 LFO2 Freq",
      "Timbre1 LFO2 Delay",
      "Timbre1 Patch1 Int",
      "Timbre1 Patch2 Int",
      "Timbre1 Patch3 Int",
      "Timbre1 Patch4 Int",
      "Timbre1 Patch5 Int",
      "Timbre1 Patch6 Int",
      "Timbre2 Unison Detune",
      "Timbre2 Unison Spread",
      "Timbre2 Porta Time",
      "Timbre2 Trans",
      "Timbre2 FineTune",
      "Timbre2 Level",
      "Timbre2 Pan",
      "Timbre2 OSC1 Wave",
      "Timbre2 OSC1 Shape",
      "Timbre2 OSC1 OSC Mod",
      "Timbre2 OSC1 Semitone",
      "Timbre2 OSC1 FineTune",
      "Timbre2 OSC1 Level",
      "Timbre2 OSC2 Wave",
      "Timbre2 OSC2 Shape",
      "Timbre2 OSC2 OSC Mod",
      "Timbre2 OSC2 Semitone",
      "Timbre2 OSC2 FineTune",
      "Timbre2 OSC2 Level",
      "Timbre2 OSC3 Wave",
      "Timbre2 OSC3 Shape",
      "Timbre2 OSC3 Semitone",
      "Timbre2 OSC3 FineTune",
      "Timbre2 OSC3 Level",
      "Timbre2 Noise Type",
      "Timbre2 Noise Color",
      "Timbre2 Noise Level",
      "Timbre2 Filter Type",
      "Timbre2 Filter Cutoff",
      "Timbre2 Filter Reso",
      "Timbre2 Filter Drive",
      "Timbre2 Filter Keytrack",
      "Timbre2 AmpEG Attack",
      "Timbre2 AmpEG Decay",
      "Timbre2 AmpEG Sustain",
      "Timbre2 AmpEG Release",
      "Timbre2 AmpEG VeloSens",
      "Timbre2 FltEG Attack",
      "Timbre2 FltEG Decay",
      "Timbre2 FltEG Sustain",
      "Timbre2 FltEG Release",
      "Timbre2 FltEG Int",
      "Timbre2 LFO1 Freq",
      "Timbre2 LFO1 Smooth",
      "Timbre2 LFO2 Freq",
      "Timbre2 LFO2 Delay",
      "Timbre2 Patch1 Int",
      "Timbre2 Patch2 Int",
      "Timbre2 Patch3 Int",
      "Timbre2 Patch4 Int",
      "Timbre2 Patch5 Int",
      "Timbre2 Patch6 Int",
      "Tempo",
      "Arp Swing",
      "Arp Reso",
      "Arp Type",
      "Arp Octave",
      "Arp Gate",
      "Arp Step",
      "Vocal Vocoder Direct",
      "Vocal Vocoder Synth",
      "Vocal Vocoder Formant",
      "Vocal Vocoder Reso",
      "Vocal Vocoder Sens",
      "Vocal Hardtune Int",
      "Vocal Hardtune Speed",
      "Vocal Hardtune Formant",
      "Vocal Harmo Level",
      "Vocal Harmo Stereo",
      "Vocal Harmo Formant",
      "Vocal Harmo Detune",
      "Vocal Harmo Delay",
      "Vocal Harmo Pitch1",
      "Vocal Harmo Pitch2",
      "Effect Mod Param1",
      "Effect Mod Param2",
      "Effect Mod Param3",
      "Effect Delay Param1",
      "Effect Delay Param2",
      "Effect Delay Param3",
      "Effect Delay Param4",
      "Effect Reverb Param1",
      "Effect Reverb Param2",
      "Effect Reverb Param3",
      "Effect Reverb Param4",
      "LoopRec Stutter",
      "EQ Low Freq",
      "EQ Low Gain",
      "EQ High Freq",
      "EQ High Gain",
      "EQ Output F.Back",
      "LoopRec Stutter Length",
      "LoopRec Stutter Offset",
    ]
    return assignKnobParameterList[value];
  }
};
